import { ReduxProvider } from '@/redux/provider'
import './styles/global.css' //how does it work??
import { ThemeProvider } from "@/components/theme-provider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <ThemeProvider>
        <body>
          <header>
            <h1 className=" font-bold text-xl text-white bg-blue-300 p-5">Header</h1>
          </header>

          <ReduxProvider>
            {children}
          </ReduxProvider>
        
        <footer>
          <h1 className=" font-bold text-xl text-white bg-purple-200 p-5">Footer</h1>
        </footer>  
        </body>
      </ThemeProvider>
      
    </html>
  )
}

