export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>
        <header>
          <h1 style={{color: "white", backgroundColor: "lightblue", padding: 10}}>Header</h1>
        </header>
      {children}
      <footer>
        <h1 style={{color: "white", backgroundColor: "lavender", padding: 10}}>Footer</h1>
      </footer>  
      </body>
      
    </html>
  )
}

